### ISSUE TITLE
Processing instructions don't really exist in HTML

### ISSUE THREAD

**Issue by domenic** [tbondwilkinson/dom-parts#5]
`<?` is just a weird way of writing `<!--?`. And `?>` is just a weird way of writing `?-->`. They are literally called ["bogus comments"](https://html.spec.whatwg.org/#bogus-comment-state).

<details>
<summary>Fun facts about bogus comments</summary>

- The other bogus comment starters are `<![CDATA[` and `<!`
- Bogus comments are closed by just `>`, not by `-->`. (So in `?>`, the "?" is just part of the comment data.)
- `<![CDATA[` and `<?` bogus comments include the text ("[CDATA[" and "?") inside the comment data. `<!` bogus comments do not include the "!".
- Bogus comments cause HTML validation errors.

http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=11764
</details>

You can see this, for example, in the live DOM viewer, which shows the resulting HTML for what it really is: comments. http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=11762

Or, try this:

```js
const div = document.createElement("div");
div.innerHTML = "<?test?>";
console.assert(div.firstChild.nodeType === Node.COMMENT_NODE);
```

So the only way I can see this proposal making sense is if it only works for XML documents.

(Or, I guess, if you are requiring everyone to create the processing instructions imperatively, using `document.createProcessingInstruction()`. But I see a lot of stuff about server-side rendering and declarative syntax in the readme, so that seems unlikely.)

I think the readme probably needs to be updated to get rid of all the bogus comment syntax, and just use normal comment syntax. And stop mentioning processing instructions, and just talk about comments.

**Comment by mfreed7** [comment]
> Fun facts about bogus comments

This was my favorite part of this comment. I learned several new fun facts. 😄 

I roughly agree with the sentiment that it's a bit odd to use "processing instructions" per se. I think the main thing we liked about them (vs pure comments) is that the syntax is a bit shorter. I.e. `<?foo?>` vs. `<!-- foo -->`. But there's also the "weirdness" factor which causes developer confusion.

It sounds like you'd be ok using a special comment syntax then? The important thing is just that it's obscure enough that won't cause compat issues with existing comments. (The extra `?` with PIs helped with this.)

What about `<!-- {{ -->` and `<!-- }} -->`?

**Comment by domenic** [comment]
To be clear, I think the main problem with using PI syntax is that it's just pre-parser input syntax, that gets erased very quickly. Once you're past the HTML parser phase, there's literally no way to tell, from either JS or browser code, whether the original code was `<?` or `<!--?`. So any feature you design to be activated by `<?` will also be activated by `<!--?`. And the latter format will be the canonical one, that is read out using DOM APIs, serialization, etc.

> It sounds like you'd be ok using a special comment syntax then? The important thing is just that it's obscure enough that won't cause compat issues with existing comments. (The extra `?` with PIs helped with this.)
> 
> What about `<!-- {{ -->` and `<!-- }} -->`?

Yep, special comment syntax seems like the only option we have, if we want to avoid parser modifications. And yeah, those options look good. Note that the spaces aren't necessary, so it can be slightly shorter!

---

Note: 

You *could* design the API around special comments that happen to use `?`. (Or `!`.) In that case, I think the way to explain it would be to put the focus around the `<!--?child-node-part?-->` syntax, since that's the canonical one. And then toward the end, you could mention something like, _by the way, you can write this in a shorter way as `<?child-node-part?>`, but that's just an authoring convenience, not the real format_. All the tooling, etc. will probably output the canonical format, but if you're hand-writing some HTML, you can do the shorter version to save typing.

Maybe there's even an analogy with other HTML parser features, like optional end tags or attribute quotes? E.g. `<p class=foo>bar` is a nice short way of writing `<p class="foo">bar</p>`. Even though the latter is the canonical format, we still often write the former in our source files, since it's nice and simple.

For maximum brevity, the combo might be something like `<!--{{-->` canonical, `<!{{>` shorthand.

Also note in this world you would probably not mention processing instructions at all, even though in XML parsers those are created by similar syntax.

**Comment by tbondwilkinson** [comment]
Work has moved to webcomponents repo, https://github.com/WICG/webcomponents/blob/gh-pages/proposals/DOM-Parts.md
