### ISSUE TITLE
Adoption context

### ISSUE THREAD

**Issue by rictic** [tbondwilkinson/dom-parts#6]
Should `partRoot.clone()` have a parameter indicating the document (or shadow root, once [Scoped Custom Element Registries](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Scoped-Custom-Element-Registries.md) have landed) that the cloned rootContainer should be adopted into?

In Lit currently we do `document.importNode(template.content, true)` to clone the template, which also upgrades custom elements, then set bound values. With `getPartRoot().clone()` we need to call customElements.upgrade on the rootContainer, which adds another tree walk after the clone.

**Comment by tbondwilkinson** [comment]
Conversation will be taking place in the webcomponents repo, see https://github.com/WICG/webcomponents/blob/gh-pages/proposals/DOM-Parts.md
